# Generated by Django 5.2.17 on 2026-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('bio', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to='profile_pics/', verbose_name='Profil rasmi')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': "Profil ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('other', 'Boshqa')], max_length=20, verbose_name='Ijtimoiy tarmoq')),
                ('url', models.URLField(verbose_name='Link (URL manzil)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami (saytda chiqish ketma-ketligi)')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video sarlavhasi')),
                ('video_url', models.URLField(verbose_name='Video linki (YouTube/Telegram/va hokazo)')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/', verbose_name='Video muqovasi (Rasm)')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['order'],
            },
        ),
    ]
