# Generated by Django 5.2.17 on 2026-08-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='Video muqovasi (Avtomatik)'),
        ),
    ]
